export default{
    path:'/movie',
    component:()=>import('@/views/Movie'),
    children:[
        {
            path:'city',
            component:()=>import('@/components/City')
        },
        {
            path:'nowplaying',
            component:()=>import('@/components/NowPlaying')
        },
        {
            path:'comingsoon',
            component:()=>import('@/components/Comingsoon')
        },
        {
            path:'search',
            component:()=>import('@/components/Search')
        },
        {
            path:'/movie',
            redirect:'/movie/nowplaying'
        },
        {
            path:'detail/np/:movieId',
            components:{
                default:()=>import('@/components/NowPlaying'),
                detail:()=>import('@/views/Movie/detail')
            },
            props:{
                detail :true
            }
        },
        {
            path:'detail/cs/:movieId',
            components:{
                default:()=>import('@/components/Comingsoon'),
                detail:()=>import('@/views/Movie/detail')
            },
            props:{
                detail :true
            }
        }
    ]
}